In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix, precision_score, recall_score, f1_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [ ]:
df=pd.read_csv('/content/X_Train_Data_Input.csv')

In [ ]:
df.isnull().sum()

ID               0
Column0          9
Column1          0
Column2          0
Column3     126303
Column4     127710
Column5     167180
Column6       3850
Column7          0
Column8       3850
Column9     732137
Column10         0
Column11         0
Column12         0
Column13         0
Column14    365703
Column15     16456
Column16         0
Column17         0
Column18         0
Column19         0
Column20         0
Column21         0
dtype: int64

In [ ]:
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

In [ ]:
categorical_columns = df.select_dtypes(include=['object', 'category', 'int64']).columns

In [ ]:
binary_columns = [col for col in categorical_columns if df[col].nunique() <= 2 and df[col].dropna().isin([0, 1]).all()]

In [ ]:
mice_imputer = IterativeImputer(max_iter=10, random_state=0)

In [ ]:
df[numerical_columns] = mice_imputer.fit_transform(df[numerical_columns])

In [ ]:
simple_imputer = SimpleImputer(strategy='most_frequent')

In [ ]:
df[binary_columns] = simple_imputer.fit_transform(df[binary_columns])

In [ ]:
df.isnull().sum()

ID          0
Column0     0
Column1     0
Column2     0
Column3     0
Column4     0
Column5     0
Column6     0
Column7     0
Column8     0
Column9     0
Column10    0
Column11    0
Column12    0
Column13    0
Column14    0
Column15    0
Column16    0
Column17    0
Column18    0
Column19    0
Column20    0
Column21    0
dtype: int64

In [ ]:
df2=pd.read_csv('/content/Y_Train_Data_Target.csv')

In [ ]:
df2.isnull().sum()

ID        0
target    0
dtype: int64

In [ ]:
df3=pd.read_csv('/content/X_Test_Data_Input.csv')

In [ ]:
df3.isnull().sum()

ID               0
Column0          2
Column1          0
Column2          0
Column3      42234
Column4      42710
Column5      55659
Column6       1234
Column7          0
Column8       1234
Column9     243853
Column10         0
Column11         0
Column12         0
Column13         0
Column14    121679
Column15      5485
Column16         0
Column17         0
Column18         0
Column19         0
Column20         0
Column21         0
dtype: int64

In [ ]:
numerical_columns = df3.select_dtypes(include=['float64', 'int64']).columns

In [ ]:
categorical_columns = df3.select_dtypes(include=['object', 'category', 'int64']).columns

In [ ]:
binary_columns = [col for col in categorical_columns if df3[col].nunique() <= 2 and df3[col].dropna().isin([0, 1]).all()]

In [ ]:
mice_imputer = IterativeImputer(max_iter=10, random_state=0)

In [ ]:
df3[numerical_columns] = mice_imputer.fit_transform(df3[numerical_columns])

In [ ]:
simple_imputer = SimpleImputer(strategy='most_frequent')

In [ ]:
df3[binary_columns] = simple_imputer.fit_transform(df3[binary_columns])

In [ ]:
df3.isnull().sum()

ID          0
Column0     0
Column1     0
Column2     0
Column3     0
Column4     0
Column5     0
Column6     0
Column7     0
Column8     0
Column9     0
Column10    0
Column11    0
Column12    0
Column13    0
Column14    0
Column15    0
Column16    0
Column17    0
Column18    0
Column19    0
Column20    0
Column21    0
dtype: int64

In [ ]:
df4=pd.read_csv('/content/Y_Test_Data_Target.csv')

In [ ]:
X_train=df.drop(columns=['ID'],axis=1)
Y_train=df2.drop(columns=['ID'],axis=1)
X_test=df3.drop(columns=['ID'],axis=1)
Y_test=df4.drop(columns=['ID'],axis=1)

In [ ]:
Y_train=Y_train.values.ravel()
Y_test=Y_test.values.ravel()

**RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from math import *

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
param_dist = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'bootstrap': [True, False]
}

In [ ]:
rf = RandomForestClassifier()
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=100, cv=3, n_jobs=-1, verbose=2, random_state=42)
random_search.fit(X_train, Y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

In [ ]:
print(random_search.best_params_)

In [ ]:

#rf=RandomForestClassifier(n_estimators=100,max_depth=None,min_samples_split=3,min_samples_leaf=1,bootstrap=True,max_features='log2')

In [ ]:
#rf.fit(X_train,Y_train)

In [ ]:
X_train_prediction=rf.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
training_data_accuracy

In [ ]:
X_test_prediction=rf.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [ ]:
test_data_accuracy

In [ ]:
precision=precision_score(Y_test,X_test_prediction)
precision

In [ ]:
recall=recall_score(Y_test,X_test_prediction)
recall

In [ ]:
f1=f1_score(Y_test,X_test_prediction)
f1

In [ ]:
cm=confusion_matrix(Y_test,X_test_prediction)
cm

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

In [ ]:
# Get the probabilities for the positive class
y_pred_proba = opt.predict_proba(X_test)[:, 1]

In [ ]:
auc_score = roc_auc_score(Y_test, y_pred_proba)
print(f"AUC Score: {auc_score}")

In [ ]:
# Compute ROC curve
fpr, tpr, thresholds = roc_curve(Y_test, y_pred_proba)

# Plot the ROC curve
plt.figure()
plt.plot(fpr, tpr, color='blue', label=f"ROC curve (area = {auc_score:.2f})")
plt.plot([0, 1], [0, 1], color='grey', linestyle='--')  # Diagonal line for random guessing
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()